dist: bionic
env: 
  global:
    DOCKER_IMAGE: arkokat/waf
jobs:
  include:
    - stage: build project
      language: java
      jdk: openjdk11
      services:
        - docker
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script:
        - mkdir -p dist/waf
        - cd src/java
        - ./gradlew build
        - ./gradlew distZip  
        - cp waf/build/distributions/waf.tar ../../dist/waf
        - cp ../docker/waf/Dockerfile ../../dist/waf
        - cd ../../dist/waf
        - docker build -t ${DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_PULL_REQUEST_BRANCH}${TRAVIS_JOB_ID} .
      after_success:
        - echo ${DOCKER_PW} | docker login -u arkokat --password-stdin
        - docker push arkokat/${DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_PULL_REQUEST_BRANCH}${TRAVIS_JOB_ID}



