dist: bionic
env: 
  global:
jobs:
  include:
    - stage: test waf project
      language: java
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
        - cd src/java
        - ./gradlew test
    - stage: build waf project
      language: java
      env:
        DOCKER_IMAGE: arkokat/waf
      jdk: openjdk11
      services:
        - docker
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script:
        - mkdir -p dist/waf
        - cd src/java
        - ./gradlew build
        - ./gradlew distZip  
        - cp waf/build/distributions/waf.tar ../../dist/waf
        - cp ../docker/waf/Dockerfile ../../dist/waf
        - cd ../../dist/waf
        - if [[ -z $TRAVIS_PULL_REQUEST_BRANCH ]]; then DOCKER_VERSION=$TRAVIS_BRANCH; else DOCKER_VERSION=$TRAVIS_BRANCH-$TRAVIS_PULL_REQUEST_BRANCH; fi
        - echo $DOCKER_IMAGE:$DOCKER_VERSION
        - docker build -t $DOCKER_IMAGE:$DOCKER_VERSION ./
      after_success:
        - echo $DOCKER_PW | docker login -u arkokat --password-stdin
        - docker push $DOCKER_IMAGE:$DOCKER_VERSION
        - if [[ "$DOCKER_VERSION" == "master" ]]; then docker tag $DOCKER_IMAGE:$DOCKER_VERSION $DOCKER_IMAGE:latest; docker push $DOCKER_IMAGE:latest; fi



