dist: disco

jobs:
  include:
    - stage: build docker image
      script: 
        - echo "$GITHUB_PACKAGES_TOKEN" | docker login docker.pkg.github.com --username arko-afeka --password-stdin
        - cd .travis
        - docker build -t waf_build .
        - docker images
        - docker tag waf_build docker.pkg.github.com/arko-afeka/finalproject/waf/build
        - docker push docker.pkg.github.com/arko-afeka/finalproject/waf_build
