dist: bionic
env: 
  global:
    DOCKER_IMAGE: waf
jobs:
  include:
    - stage: build waf
      language: java
      jdk: openjdk11
      services:
        - docker
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script:
        - cd core
        - mkdir dist
        - ./gradlew build
        - ./gradlew distZip  
        - cp waf/build/distributions/waf.tar dist
        - cp waf/Dockerfile dist
        - cd dist
        - docker build -t ${DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_PULL_REQUEST_BRANCH}${TRAVIS_JOB_ID} .
      after_sucess:
        - docker login -u arkokat -p ${DOCKER_PW}
        - docker push ${DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_PULL_REQUEST_BRANCH}${TRAVIS_JOB_ID}



