dist: disco

env: 
  global:
    DOCKER_IMAGE: docker.pkg.github.com/arko-afeka/finalproject/waf_build
jobs:
  include:
    - stage: build docker image
      before_script:
        - echo "$GITHUB_PACKAGES_TOKEN" | docker login docker.pkg.github.com --username arko-afeka --password-stdin
        - docker pull $DOCKER_IMAGE:latest || true
      script: 
        - cd .travis
        - docker build --cache-from $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:latest .
        - docker images
      after_success:
        - docker push $DOCKER_IMAGE:latest

