dist: bionic
env: 
  global:
    DOCKER_REGISTRY: docker.pkg.github.com
    DOCKER_IMAGE: docker.pkg.github.com/arko-afeka/finalproject/waf_build
jobs:
  include:
    # - stage: build docker image
    #   script: 
    #     - cd .travis
    #     - docker build --cache-from $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:latest .
    #     - docker images
    #   after_success:
    #     - docker push $DOCKER_IMAGE:latest

    - stage: build project
      language: java
      jdk: openjdk11
      services:
        - docker
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script:
        - cd src/java
        - ./gradlew build
        - ./gradlew distZip  
        - cd waf/build/distributions
        - echo "$GITHUB_PACKAGES_TOKEN" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USERNAME --password-stdin
        - docker pull $DOCKER_IMAGE:latest || true
        - docker build -f ~/src/docker/Dockerfile -t $DOCKER_IMAGE:latest ./




