dist: bionic
env: 
  global:
    DOCKER_REGISTRY: docker.pkg.github.com
    DOCKER_IMAGE: docker.pkg.github.com/arko-afeka/finalproject/waf_build
jobs:
  include:
    # - stage: build docker image
    #   script: 
    #     - cd .travis
    #     - docker build --cache-from $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:latest .
    #     - docker images
    #   after_success:
    #     - docker push $DOCKER_IMAGE:latest

    - stage: build project
      language: java
      jdk: openjdk11
      services:
        - docker
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script:
        - mkdir $TRAVIS_BUILD_DIR/dist
        - mkdir $TRAVIS_BUILD_DIR/dist/waf
        - cd $TRAVIS_BUILD_DIR/src/java
        - ./gradlew build
        - ./gradlew distZip  
        - cd $TRAVIS_BUILD_DIR
        - cp $TRAVIS_BUILD_DIR/src/java/waf/build/distributions/waf.tar $TRAVIS_BUILD_DIR/dist/waf
        - cp $TRAVIS_BUILD_DIR/src/docker/waf/Dockerfile $TRAVIS_BUILD_DIR/dist/waf
        - cd $TRAVIS_BUILD_DIR/dist/waf
        - echo "$GITHUB_PACKAGES_TOKEN" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USERNAME --password-stdin
        - docker pull $DOCKER_IMAGE:latest || true
        - docker build -t $DOCKER_IMAGE:latest .
      deploy:
        provider: script
        script:
          - docker tag $DOCKER_IMAGE:latest registry.heroku.com/arkokat-afeka-waf-staging/server
          - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
          - docker push registry.heroku.com/arkokat-afeka-waf-staging/server




